name: Deploy to AWS

on:
  workflow_dispatch:
permissions:
      id-token: write
      contents: read       

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      ECR_REPOSITORY: my-sqs-dynamodb-app
      ECS_CLUSTER: td-sqs-trigger
      ECS_SERVICE: td-sqs-trigger

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
           role-to-assume: arn:aws:iam::933085737869:role/github-OIDC-Connect
           aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get the latest task definition for the specified family
        id: taskdef
        run: |
           FAMILY_NAME="td_MPulseQSInitial"
           LATEST_TASK_DEF_ARN=$(aws ecs list-task-definitions --family-prefix $FAMILY_NAME --sort DESC --query "taskDefinitionArns[0]" --output text)
           echo "LATEST_TASK_DEF_ARN=$LATEST_TASK_DEF_ARN" >> $GITHUB_ENV

      - name: Update ECS service with the new task definition
        run: |
         CLUSTER_NAME="my-cluster"
         SERVICE_NAME="my-service"
         aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --task-definition ${{ env.LATEST_TASK_DEF_ARN }}
